    CREATE DATABASE gasolinera;
    GO
    USE gasolinera
    GO

    CREATE TABLE CLIENTE(
        ID_CLIENTE INT NOT NULL PRIMARY KEY,
        NOMBRE VARCHAR(200),
        APELLIDO VARCHAR,
        DIRECCION VARCHAR,
        TELEFONO VARCHAR,
        PUNTOS INT
    )
    GO
    CREATE TABLE EMPLEADO(
        ID_EMPLEADO INT NOT NULL PRIMARY KEY,
        NOMBRE  VARCHAR(150),
        CARGO VARCHAR(100),
        TELEFONO VARCHAR(20)
    )
    GO
    CREATE TABLE VENTA(
        ID_VENTA INT NOT NULL PRIMARY KEY,
        ID_EMPLEADO INT,
        ID_CLIENTE INT,
        PRECIO REAL,
        IMPUENTO_F REAL,
        IVA REAL,
        TOTAL REAL,
        CONSTRAINT fk_Empleado FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
        CONSTRAINT fk_Cliente FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
    )
    GO
    CREATE TABLE GASOLINA(
        ID_GASOLINA INT NOT NULL PRIMARY KEY,
        NOMBRE VARCHAR
    )
    GO
    CREATE TABLE PROVEEDOR(
        ID_PROVEEDOR INT NOT NULL PRIMARY KEY,
        NOMBRE VARCHAR(200),
        APELLIDO VARCHAR,
        DIRECCION VARCHAR,
        TELEFONO VARCHAR
    )
    GO
    CREATE TABLE BOMBA(
        ID_BOMBA INT NOT NULL PRIMARY KEY,
        CANTIDAD_GALON REAL,
        ID_GASOLINA INT NOT NULL,
        ID_PROVEEDOR INT NOT NULL,
        CONSTRAINT fk_Gasilan FOREIGN KEY (ID_GASOLINA) REFERENCES  GASOLINA (ID_GASOLINA),
        CONSTRAINT fk_Proveedor FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR)        
    )
    GO
    CREATE TABLE DETALLE_VENTA(
        ID_DETALLE INT NOT NULL PRIMARY KEY,
        ID_BOMBA INT NOT NULL,
        ID_VENTA INT NOT NULL,
        CANTIDAD REAL,
        DESCUENTO REAL,
        PRECIO REAL,
        CONSTRAINT fk_bomba FOREIGN KEY (ID_BOMBA) REFERENCES BOMBA (ID_BOMBA),
        CONSTRAINT fk_VENTA FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID_VENTA)
    )
    GO
    CREATE TABLE TRANSACCION(
        ID_TRAN INT NOT NULL PRIMARY KEY,
        MONTO_IN REAL,
        MONTO_OUT REAL,
        ID_VENTA INT ,
        CONSTRAINT fk_VENTA2 FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID_VENTA)
    )

